.github/workflows/build-and-upload.yaml, README.md
This replaces the version in the document built from the main branch with a warning that it wasn't yet released:
=> Add variables to publish job

main.tex
Replace magic number paragraph changes to \par.
=> Change paragraph spacing to a defined variable

main.tex, sections/all_map_locations.tex, sections/deckbuilding.tex, sections/other_rules.tex, sections/player_turns.tex, sections/units.tex
Changes:
- Better looking section header
- Locations use smaller text as captions to better use page space
- Introduced some wrapfigures around pictures ending subsections
=> Introduce layout tweaks

sections/combat.tex, sections/units.tex
Fixed two typoes spotted by discord user Ksenon before I forget about them.
=> Fix typoes

sections/all_map_locations.tex, sections/combat.tex, sections/credits.tex, sections/expansion_content.tex
Expanded the description of attacking walls, fixed and made consistent many descriptions in the expansion and location sections by including svg images and Capitalizing certain terms.
=> Small fixes and corrections

main.tex, sections/combat.tex, sections/deckbuilding.tex, sections/expansion_content.tex, sections/game_modes.tex, sections/heroes.tex, sections/other_rules.tex, sections/player_turns.tex, sections/setup.tex, sections/town.tex, sections/units.tex
=> Expand index

sections/ai_heroes.tex, sections/all_map_locations.tex, sections/combat.tex, sections/credits.tex, sections/deckbuilding.tex, sections/game_modes.tex, sections/heroes.tex, sections/introduction.tex, sections/map_elements.tex, sections/player_turns.tex, sections/resources.tex, sections/round_structure.tex, sections/scenario_end.tex, sections/setup.tex, sections/town.tex, sections/units.tex
Small fixes in language as pointed out by my fiancé (aka Narylfiel in the credits). Also added many new people there. I'll probably stop doing that soon since I've already technically missed a billion people who have reached out or commented the project on discord.
=> Proofreading and fixing

components_lists/core_game.tex
=> Fix hero count for core game

make_printable.sh
The non-controversial part of #159
=> Add index again

components_lists/strech_goals_neutral.tex
According to others, myself included - there are 10 Plastic Coins (1)
=> Update plastic coin (1) count from 11 -> 10

.github/CODEOWNERS, sections/player_turns.tex, translations/player_turns.tex/es.po, translations/player_turns.tex/pl.po, translations/player_turns.tex/player_turns.tex.pot
=> Fix typo in player turns

translations/scenario_end.tex/es.po
=> [ES] Scenario End

components_lists/battlefield.tex, components_lists/tower.tex
=> Fix card header count errors

translations/notes.tex/es.po
=> [ES] Notes

translations/deckbuilding.tex/es.po, translations/round_structure.tex/es.po
=> [ES] Deck Building

po4a.cfg, translations/back_cover.tex/back_cover.tex.pot, translations/back_cover.tex/es.po, translations/back_cover.tex/fr.po, translations/back_cover.tex/pl.po, translations/deckbuilding.tex/es.po, translations/difficulty.tex/fr.po, translations/expansion_content.tex/es.po, translations/expansion_content.tex/expansion_content.tex.pot, translations/expansion_content.tex/fr.po, translations/expansion_content.tex/pl.po, translations/heroes.tex/es.po, translations/heroes.tex/fr.po, translations/heroes.tex/heroes.tex.pot, translations/heroes.tex/pl.po, translations/introduction.tex/es.po, translations/introduction.tex/fr.po, translations/notes.tex/fr.po, translations/round_structure.tex/es.po, translations/setup.tex/es.po, translations/setup.tex/fr.po, translations/setup.tex/pl.po, translations/setup.tex/setup.tex.pot, translations/town.tex/es.po, translations/units.tex/es.po, translations/units.tex/fr.po, translations/units.tex/pl.po, translations/units.tex/units.tex.pot
po4a update, changed back_cover verbatim to tikzpicture,figure
=> po4a update

sections/resources.tex, translations/expansion_content.tex/pl.po, translations/resources.tex/es.po, translations/resources.tex/fr.po, translations/resources.tex/pl.po, translations/resources.tex/resources.tex.pot
Look at the resource die results (before|after):
=> Fix hyphens and font size in Resources section

translations/ai_heroes.tex/es.po
=> [ES] AI Heroes

translations/difficulty.tex/es.po
Strange, but the tittle didn't change @qwrtln
=> [ES] Dificulty

translations/map_elements.tex/es.po
=> [ES] Map Elements

sections/units.tex, translations/units.tex/es.po, translations/units.tex/fr.po, translations/units.tex/pl.po, translations/units.tex/ru.po, translations/units.tex/units.tex.pot
=> Fix empty page after Units table in printable

README.md
Some stuff is outdated, other stuff is incorrect.
=> Clear up readme

translations/round_structure.tex/ua.po
=> [UA] Round Structure

translations/resources.tex/ua.po
=> [UA] Resources

tools/compare_pages.sh
=> Use mktemp

translations/combat.tex/fr.po
=> [FR]Fix-Combat.po

translations/ai_rules.tex/ua.po
=> [UA] AI Rules

.github/workflows/build-and-publish-rule-book.yaml, README.md, tools/optimize.sh
This reduces PDF size significantly.
=> Use ghostscript to compress workflow PDFs

translations/ai_rules.tex/es.po, translations/ai_rules.tex/fr.po, translations/ai_rules.tex/pl.po
=> Restore coin size, make translations on the same page fuzzy to make it

translations/units.tex/es.po
Just a fix on text translation.
=> [ES] Fix text

main_es.tex, translations/credits.tex/es.po
=> [ES] Quote fix

translations/units.tex/fr.po
=> [fr] unit translation Update fr.po

translations/combat.tex/fr.po
=> [fr] combat Update fr.po

README.md, translations/ai_rules.tex/cs.po, translations/game_modes.tex/cs.po, translations/scenario_end.tex/cs.po
=> [CS] game modes

.gitignore, README.md, tools/clean.sh, tools/compare_pages.sh
RFC. Created as a reaction to stalled PR https://github.com/Heegu-sama/Homm3BG/pull/417 on the same topic for my own purpose
The main thing here is that you don't need to build the baselines, it downloads the latest build from here for comparison and supports regular and printable versions
If you find this useful in general, I can create a proper PR from it
=> Custom compare pages script

.github/workflows/build-and-publish-rule-book.yaml
=> Download less artifacts during CI

translations/introduction.tex/he.po
Something strange that happened now
I need to add \\texthebrew inside notes and addsection, without it it doesn't print anything.
A little bit annoying, but nothing that can't be handle inside the translation itself
=> [HE] introduction

translations/credits.tex/ru.po
=> [RU] credits

translations/resources.tex/pl.po
=> [PL] Fix valuables

translations/scenario_end.tex/he.po
=> [HE] scenario end

translations/credits.tex/he.po
I don't think it is right to try and write the names in Hebrew letters.
=> [HE] credits

metadata.tex, translations/all_map_locations.tex/es.po, translations/round_structure.tex/es.po
=> [ES] Split long titles into 2 lines

README.md
=> Give readme a little more modern look

sections/deckbuilding.tex, translations/deckbuilding.tex/cs.po, translations/deckbuilding.tex/de.po, translations/deckbuilding.tex/deckbuilding.tex.pot, translations/deckbuilding.tex/es.po, translations/deckbuilding.tex/fr.po, translations/deckbuilding.tex/he.po, translations/deckbuilding.tex/pl.po, translations/deckbuilding.tex/ru.po, translations/deckbuilding.tex/ua.po
This reverts commit 01fe9c48a56cc632f8219984fe0c28bca48bd2f4. #749
This should be reapplied after 1.3
=> Revert "New SP clarification (#749)"

.github/workflows/build-and-publish-rule-book.yaml, .github/workflows/build-release.yaml, README.md, tools/optimize.sh, tools/release.sh
This is a workflow of convenience, which makes building release files easy. The PR also updates the optimize script with experimental monochrome build.
See the [workflow result](https://github.com/Heegu-sama/Homm3BG/actions/runs/11857453520).
=> Create release pipeline

po4a.cfg
po4a merges those arguments anyway.
=> Cleanup in po4a.cfg

translations/index.tex/de.po, translations/notes.tex/de.po
=> [DE] Translation Index, Notes

translations/units.tex/pl.po
=> [PL] Fix unit card header

translations/ai_rules.tex/pl.po, translations/game_modes.tex/pl.po, translations/prompt.txt/pl.po
=> [PL] Unfuzzy game modes and AI

README.md
=> Fix invalid Discord link

sections/map_elements.tex, translations/map_elements.tex/cs.po, translations/map_elements.tex/de.po, translations/map_elements.tex/es.po, translations/map_elements.tex/fr.po, translations/map_elements.tex/he.po, translations/map_elements.tex/map_elements.tex.pot, translations/map_elements.tex/pl.po, translations/map_elements.tex/ru.po, translations/map_elements.tex/ua.po
=> Add small clarification and fix link

translations/difficulty.tex/ru.po
=> [RU] difficulty

translations/combat.tex/ru.po
=> [RU] Combat
